---
spec/spec_helper.rb:
  facterdb_string_keys: true
  spec_overrides:
    - "Dir['./spec/support/**/*.rb'].sort.each { |f| require f }"
spec/spec_helper_acceptance.rb:
  unmanaged: false
.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_types
